### ISSUE TITLE
AADSTS65001: The user or administrator has not consented to use the application with ID

### ISSUE THREAD

**Issue by Jayakrishnantu** [Azure-Samples/ms-identity-java-desktop#10]
Hello,

I am following this document https://docs.microsoft.com/en-us/samples/azure-samples/ms-identity-java-desktop/call-msgraph-with-username-password/ and seeing the following issue.

[ForkJoinPool.commonPool-worker-9] ERROR com.microsoft.aad.msal4j.PublicClientApplication - [Correlation ID: 6ed3f887-f7a7-4201-ba9c-6587d8510ef8] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID 'ab8dd9d6-d79b-454d-9c40-236a74cfe698' named 'AzureTestApp01'. Send an interactive authorization request for this user and resource.
Trace ID: 0eb3ee9e-b1c1-43e8-90b3-2a1a70b71100
Correlation ID: 6ed3f887-f7a7-4201-ba9c-6587d8510ef8
Timestamp: 2020-06-19 22:32:40Z

I have followed the steps.
- Registered the app ad Public client
- updated Manifest to set allowPublicClient property to true
- set the User.Read permission
- also given Grant/revoke admin consent

I have referred multiple articles to resolve this; but none worked. Any pointers will be helpful.

**Comment by Avery-Dunn** [comment]
Hello, just to confirm [admin consent](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent) being granted could you go to the `API Permissions` section of your app registration, and check under the 'status' column to see if it looks similar to this:

![image](https://user-images.githubusercontent.com/62066438/85434516-0502f800-b53b-11ea-84d8-b65e5d89b33b.png)
(I added the user.read.all permission just to show what a not-granted permission would look like, for the sample you should only need user.read)

If there is either a yellow exclamation mark(like in the image above) or it is blank, then something may have gone wrong when granting admin consent and you should try the 'grant consent for {tenant}' button again.

**Comment by Jayakrishnantu** [comment]
> Hello, just to confirm [admin consent](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent) being granted could you go to the `API Permissions` section of your app registration, and check under the 'status' column to see if it looks similar to this:
> 
> ![image](https://user-images.githubusercontent.com/62066438/85434516-0502f800-b53b-11ea-84d8-b65e5d89b33b.png)
> (I added the user.read.all permission just to show what a not-granted permission would look like, for the sample you should only need user.read)
> 
> If there is either a yellow exclamation mark(like in the image above) or it is blank, then something may have gone wrong when granting admin consent and you should try the 'grant consent for {tenant}' button again.

I have the Green status for both the APIs. Posting the solution below.

**Comment by Jayakrishnantu** [comment]
The approach has changed. Should have been using the ROPC flow test to get the access token. Details below. 
https://stackoverflow.com/questions/62494916/aadsts65001-the-user-or-administrator-has-not-consented-to-use-the-application
